### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by kort3x** [nicollasricas/vscode-streamdeck#3]
Maybe it's me but i find it hard to get started using this.

Like for example:
%appdata%\Elgato\StreamDeck\Plugins\com.nicollasr.streamdeckvsc.sdPlugin\appsettings.json
does not exist. Do I have to create it?

Could you eleborate on how to get going?

**Comment by nicollasricas** [comment]
No, the only reason to create/edit this file is to change the server port wen used by other software.

If you had installed the Stream Deck plugin and also the Visual Studio Code extension, it should work.

This may help: [https://github.com/nicollasricas/streamdeckvsc/issues/1](https://github.com/nicollasricas/streamdeckvsc/issues/1).

Let me know if this works.

I will add a note that change settings are an optional step because you don't have to do anything besides have the plugin on Stream Deck side and the extension on Visual Studio Code (done by the plugin installation) side installed.

**Comment by kort3x** [comment]
Now it works.
In the status bar it used to to say only  "Deck | Connected"
After a few restarts of vs code it now says "Deck | Connected | Active". Not sure what changed but OK.

Thank!

**Comment by nicollasricas** [comment]
If for some reason it's not active just use alt+tab it will activate it. I couldn't figure out another way to identify which instance of VS Code is active when multiple instances are running.

Ty!

**Comment by Ajwah** [comment]
Regardless as to what I do, my window does not get designated as `Active`

<img width="196" alt="Screen Shot 2020-05-01 at 3 41 19 PM" src="https://user-images.githubusercontent.com/11848116/80836182-34902680-8bc2-11ea-9b55-9df00c6c8836.png">

Restarting a few times;  CMD + Tab or Alt + Tab did not work
